// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: PersonMsg.proto

package unit.serializer.protobuf;


public final class PersonMsg {
  private PersonMsg() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  /**
   * Protobuf enum {@code Sex}
   *
   * <pre>
   *枚举类
   * </pre>
   */
  public enum Sex
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>MALE = 0;</code>
     */
    MALE(0, 0),
    /**
     * <code>FEMALE = 1;</code>
     */
    FEMALE(1, 1),
    ;

    /**
     * <code>MALE = 0;</code>
     */
    public static final int MALE_VALUE = 0;
    /**
     * <code>FEMALE = 1;</code>
     */
    public static final int FEMALE_VALUE = 1;


    public final int getNumber() { return value; }

    public static Sex valueOf(int value) {
      switch (value) {
        case 0: return MALE;
        case 1: return FEMALE;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<Sex>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static com.google.protobuf.Internal.EnumLiteMap<Sex>
        internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<Sex>() {
            public Sex findValueByNumber(int number) {
              return Sex.valueOf(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(index);
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return PersonMsg.getDescriptor().getEnumTypes().get(0);
    }

    private static final Sex[] VALUES = values();

    public static Sex valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      return VALUES[desc.getIndex()];
    }

    private final int index;
    private final int value;

    private Sex(int index, int value) {
      this.index = index;
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:Sex)
  }

  public interface InfoOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // optional int32 qq = 1;
    /**
     * <code>optional int32 qq = 1;</code>
     */
    boolean hasQq();
    /**
     * <code>optional int32 qq = 1;</code>
     */
    int getQq();

    // optional int32 weixin = 2;
    /**
     * <code>optional int32 weixin = 2;</code>
     */
    boolean hasWeixin();
    /**
     * <code>optional int32 weixin = 2;</code>
     */
    int getWeixin();
  }
  /**
   * Protobuf type {@code Info}
   */
  public static final class Info extends
      com.google.protobuf.GeneratedMessage
      implements InfoOrBuilder {
    // Use Info.newBuilder() to construct.
    private Info(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private Info(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final Info defaultInstance;
    public static Info getDefaultInstance() {
      return defaultInstance;
    }

    public Info getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private Info(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              qq_ = input.readInt32();
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              weixin_ = input.readInt32();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return PersonMsg.internal_static_Info_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return PersonMsg.internal_static_Info_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              PersonMsg.Info.class, PersonMsg.Info.Builder.class);
    }

    public static com.google.protobuf.Parser<Info> PARSER =
        new com.google.protobuf.AbstractParser<Info>() {
      public Info parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Info(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<Info> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // optional int32 qq = 1;
    public static final int QQ_FIELD_NUMBER = 1;
    private int qq_;
    /**
     * <code>optional int32 qq = 1;</code>
     */
    public boolean hasQq() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional int32 qq = 1;</code>
     */
    public int getQq() {
      return qq_;
    }

    // optional int32 weixin = 2;
    public static final int WEIXIN_FIELD_NUMBER = 2;
    private int weixin_;
    /**
     * <code>optional int32 weixin = 2;</code>
     */
    public boolean hasWeixin() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional int32 weixin = 2;</code>
     */
    public int getWeixin() {
      return weixin_;
    }

    private void initFields() {
      qq_ = 0;
      weixin_ = 0;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1, qq_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeInt32(2, weixin_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, qq_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, weixin_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static PersonMsg.Info parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static PersonMsg.Info parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static PersonMsg.Info parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static PersonMsg.Info parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static PersonMsg.Info parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static PersonMsg.Info parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static PersonMsg.Info parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static PersonMsg.Info parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static PersonMsg.Info parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static PersonMsg.Info parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(PersonMsg.Info prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code Info}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements PersonMsg.InfoOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return PersonMsg.internal_static_Info_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return PersonMsg.internal_static_Info_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                PersonMsg.Info.class, PersonMsg.Info.Builder.class);
      }

      // Construct using PersonMsg.Info.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        qq_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        weixin_ = 0;
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return PersonMsg.internal_static_Info_descriptor;
      }

      public PersonMsg.Info getDefaultInstanceForType() {
        return PersonMsg.Info.getDefaultInstance();
      }

      public PersonMsg.Info build() {
        PersonMsg.Info result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public PersonMsg.Info buildPartial() {
        PersonMsg.Info result = new PersonMsg.Info(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.qq_ = qq_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.weixin_ = weixin_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof PersonMsg.Info) {
          return mergeFrom((PersonMsg.Info)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(PersonMsg.Info other) {
        if (other == PersonMsg.Info.getDefaultInstance()) return this;
        if (other.hasQq()) {
          setQq(other.getQq());
        }
        if (other.hasWeixin()) {
          setWeixin(other.getWeixin());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        PersonMsg.Info parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (PersonMsg.Info) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // optional int32 qq = 1;
      private int qq_ ;
      /**
       * <code>optional int32 qq = 1;</code>
       */
      public boolean hasQq() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional int32 qq = 1;</code>
       */
      public int getQq() {
        return qq_;
      }
      /**
       * <code>optional int32 qq = 1;</code>
       */
      public Builder setQq(int value) {
        bitField0_ |= 0x00000001;
        qq_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 qq = 1;</code>
       */
      public Builder clearQq() {
        bitField0_ = (bitField0_ & ~0x00000001);
        qq_ = 0;
        onChanged();
        return this;
      }

      // optional int32 weixin = 2;
      private int weixin_ ;
      /**
       * <code>optional int32 weixin = 2;</code>
       */
      public boolean hasWeixin() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional int32 weixin = 2;</code>
       */
      public int getWeixin() {
        return weixin_;
      }
      /**
       * <code>optional int32 weixin = 2;</code>
       */
      public Builder setWeixin(int value) {
        bitField0_ |= 0x00000002;
        weixin_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 weixin = 2;</code>
       */
      public Builder clearWeixin() {
        bitField0_ = (bitField0_ & ~0x00000002);
        weixin_ = 0;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:Info)
    }

    static {
      defaultInstance = new Info(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:Info)
  }

  public interface PersonOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // required int32 id = 1;
    /**
     * <code>required int32 id = 1;</code>
     *
     * <pre>
     *=后面的数字好像就是序号,一直排下来就是了
     * </pre>
     */
    boolean hasId();
    /**
     * <code>required int32 id = 1;</code>
     *
     * <pre>
     *=后面的数字好像就是序号,一直排下来就是了
     * </pre>
     */
    int getId();

    // required string name = 2;
    /**
     * <code>required string name = 2;</code>
     */
    boolean hasName();
    /**
     * <code>required string name = 2;</code>
     */
    java.lang.String getName();
    /**
     * <code>required string name = 2;</code>
     */
    com.google.protobuf.ByteString
        getNameBytes();

    // optional string email = 3;
    /**
     * <code>optional string email = 3;</code>
     */
    boolean hasEmail();
    /**
     * <code>optional string email = 3;</code>
     */
    java.lang.String getEmail();
    /**
     * <code>optional string email = 3;</code>
     */
    com.google.protobuf.ByteString
        getEmailBytes();

    // repeated string friends = 4;
    /**
     * <code>repeated string friends = 4;</code>
     */
    java.util.List<java.lang.String>
    getFriendsList();
    /**
     * <code>repeated string friends = 4;</code>
     */
    int getFriendsCount();
    /**
     * <code>repeated string friends = 4;</code>
     */
    java.lang.String getFriends(int index);
    /**
     * <code>repeated string friends = 4;</code>
     */
    com.google.protobuf.ByteString
        getFriendsBytes(int index);

    // required .Sex sex = 5;
    /**
     * <code>required .Sex sex = 5;</code>
     *
     * <pre>
     *引用枚举
     * </pre>
     */
    boolean hasSex();
    /**
     * <code>required .Sex sex = 5;</code>
     *
     * <pre>
     *引用枚举
     * </pre>
     */
    PersonMsg.Sex getSex();

    // optional .Info info = 6;
    /**
     * <code>optional .Info info = 6;</code>
     *
     * <pre>
     *引用message
     * </pre>
     */
    boolean hasInfo();
    /**
     * <code>optional .Info info = 6;</code>
     *
     * <pre>
     *引用message
     * </pre>
     */
    PersonMsg.Info getInfo();
    /**
     * <code>optional .Info info = 6;</code>
     *
     * <pre>
     *引用message
     * </pre>
     */
    PersonMsg.InfoOrBuilder getInfoOrBuilder();

    // optional .Person.Score score = 7;
    /**
     * <code>optional .Person.Score score = 7;</code>
     *
     * <pre>
     *引用嵌套message
     * </pre>
     */
    boolean hasScore();
    /**
     * <code>optional .Person.Score score = 7;</code>
     *
     * <pre>
     *引用嵌套message
     * </pre>
     */
    PersonMsg.Person.Score getScore();
    /**
     * <code>optional .Person.Score score = 7;</code>
     *
     * <pre>
     *引用嵌套message
     * </pre>
     */
    PersonMsg.Person.ScoreOrBuilder getScoreOrBuilder();
  }
  /**
   * Protobuf type {@code Person}
   *
   * <pre>
   *3.0版本不写限定符默认都是optional
   *optional,可选,3.0版本没有了
   *required,必须要的,3.0版本没有了
   *repeated,重复的,对应java的list
   * </pre>
   */
  public static final class Person extends
      com.google.protobuf.GeneratedMessage
      implements PersonOrBuilder {
    // Use Person.newBuilder() to construct.
    private Person(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private Person(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final Person defaultInstance;
    public static Person getDefaultInstance() {
      return defaultInstance;
    }

    public Person getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private Person(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              id_ = input.readInt32();
              break;
            }
            case 18: {
              bitField0_ |= 0x00000002;
              name_ = input.readBytes();
              break;
            }
            case 26: {
              bitField0_ |= 0x00000004;
              email_ = input.readBytes();
              break;
            }
            case 34: {
              if (!((mutable_bitField0_ & 0x00000008) == 0x00000008)) {
                friends_ = new com.google.protobuf.LazyStringArrayList();
                mutable_bitField0_ |= 0x00000008;
              }
              friends_.add(input.readBytes());
              break;
            }
            case 40: {
              int rawValue = input.readEnum();
              PersonMsg.Sex value = PersonMsg.Sex.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(5, rawValue);
              } else {
                bitField0_ |= 0x00000008;
                sex_ = value;
              }
              break;
            }
            case 50: {
              PersonMsg.Info.Builder subBuilder = null;
              if (((bitField0_ & 0x00000010) == 0x00000010)) {
                subBuilder = info_.toBuilder();
              }
              info_ = input.readMessage(PersonMsg.Info.PARSER, extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(info_);
                info_ = subBuilder.buildPartial();
              }
              bitField0_ |= 0x00000010;
              break;
            }
            case 58: {
              PersonMsg.Person.Score.Builder subBuilder = null;
              if (((bitField0_ & 0x00000020) == 0x00000020)) {
                subBuilder = score_.toBuilder();
              }
              score_ = input.readMessage(PersonMsg.Person.Score.PARSER, extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(score_);
                score_ = subBuilder.buildPartial();
              }
              bitField0_ |= 0x00000020;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000008) == 0x00000008)) {
          friends_ = new com.google.protobuf.UnmodifiableLazyStringList(friends_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return PersonMsg.internal_static_Person_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return PersonMsg.internal_static_Person_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              PersonMsg.Person.class, PersonMsg.Person.Builder.class);
    }

    public static com.google.protobuf.Parser<Person> PARSER =
        new com.google.protobuf.AbstractParser<Person>() {
      public Person parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Person(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<Person> getParserForType() {
      return PARSER;
    }

    public interface ScoreOrBuilder
        extends com.google.protobuf.MessageOrBuilder {

      // optional int32 chinese = 1;
      /**
       * <code>optional int32 chinese = 1;</code>
       */
      boolean hasChinese();
      /**
       * <code>optional int32 chinese = 1;</code>
       */
      int getChinese();

      // optional int32 history = 2;
      /**
       * <code>optional int32 history = 2;</code>
       */
      boolean hasHistory();
      /**
       * <code>optional int32 history = 2;</code>
       */
      int getHistory();
    }
    /**
     * Protobuf type {@code Person.Score}
     *
     * <pre>
     *嵌套
     * </pre>
     */
    public static final class Score extends
        com.google.protobuf.GeneratedMessage
        implements ScoreOrBuilder {
      // Use Score.newBuilder() to construct.
      private Score(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
        super(builder);
        this.unknownFields = builder.getUnknownFields();
      }
      private Score(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

      private static final Score defaultInstance;
      public static Score getDefaultInstance() {
        return defaultInstance;
      }

      public Score getDefaultInstanceForType() {
        return defaultInstance;
      }

      private final com.google.protobuf.UnknownFieldSet unknownFields;
      @java.lang.Override
      public final com.google.protobuf.UnknownFieldSet
          getUnknownFields() {
        return this.unknownFields;
      }
      private Score(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        initFields();
        int mutable_bitField0_ = 0;
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
            com.google.protobuf.UnknownFieldSet.newBuilder();
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              default: {
                if (!parseUnknownField(input, unknownFields,
                                       extensionRegistry, tag)) {
                  done = true;
                }
                break;
              }
              case 8: {
                bitField0_ |= 0x00000001;
                chinese_ = input.readInt32();
                break;
              }
              case 16: {
                bitField0_ |= 0x00000002;
                history_ = input.readInt32();
                break;
              }
            }
          }
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(this);
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(
              e.getMessage()).setUnfinishedMessage(this);
        } finally {
          this.unknownFields = unknownFields.build();
          makeExtensionsImmutable();
        }
      }
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return PersonMsg.internal_static_Person_Score_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return PersonMsg.internal_static_Person_Score_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                PersonMsg.Person.Score.class, PersonMsg.Person.Score.Builder.class);
      }

      public static com.google.protobuf.Parser<Score> PARSER =
          new com.google.protobuf.AbstractParser<Score>() {
        public Score parsePartialFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
          return new Score(input, extensionRegistry);
        }
      };

      @java.lang.Override
      public com.google.protobuf.Parser<Score> getParserForType() {
        return PARSER;
      }

      private int bitField0_;
      // optional int32 chinese = 1;
      public static final int CHINESE_FIELD_NUMBER = 1;
      private int chinese_;
      /**
       * <code>optional int32 chinese = 1;</code>
       */
      public boolean hasChinese() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional int32 chinese = 1;</code>
       */
      public int getChinese() {
        return chinese_;
      }

      // optional int32 history = 2;
      public static final int HISTORY_FIELD_NUMBER = 2;
      private int history_;
      /**
       * <code>optional int32 history = 2;</code>
       */
      public boolean hasHistory() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional int32 history = 2;</code>
       */
      public int getHistory() {
        return history_;
      }

      private void initFields() {
        chinese_ = 0;
        history_ = 0;
      }
      private byte memoizedIsInitialized = -1;
      public final boolean isInitialized() {
        byte isInitialized = memoizedIsInitialized;
        if (isInitialized != -1) return isInitialized == 1;

        memoizedIsInitialized = 1;
        return true;
      }

      public void writeTo(com.google.protobuf.CodedOutputStream output)
                          throws java.io.IOException {
        getSerializedSize();
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          output.writeInt32(1, chinese_);
        }
        if (((bitField0_ & 0x00000002) == 0x00000002)) {
          output.writeInt32(2, history_);
        }
        getUnknownFields().writeTo(output);
      }

      private int memoizedSerializedSize = -1;
      public int getSerializedSize() {
        int size = memoizedSerializedSize;
        if (size != -1) return size;

        size = 0;
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          size += com.google.protobuf.CodedOutputStream
            .computeInt32Size(1, chinese_);
        }
        if (((bitField0_ & 0x00000002) == 0x00000002)) {
          size += com.google.protobuf.CodedOutputStream
            .computeInt32Size(2, history_);
        }
        size += getUnknownFields().getSerializedSize();
        memoizedSerializedSize = size;
        return size;
      }

      private static final long serialVersionUID = 0L;
      @java.lang.Override
      protected java.lang.Object writeReplace()
          throws java.io.ObjectStreamException {
        return super.writeReplace();
      }

      public static PersonMsg.Person.Score parseFrom(
          com.google.protobuf.ByteString data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static PersonMsg.Person.Score parseFrom(
          com.google.protobuf.ByteString data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static PersonMsg.Person.Score parseFrom(byte[] data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static PersonMsg.Person.Score parseFrom(
          byte[] data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static PersonMsg.Person.Score parseFrom(java.io.InputStream input)
          throws java.io.IOException {
        return PARSER.parseFrom(input);
      }
      public static PersonMsg.Person.Score parseFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return PARSER.parseFrom(input, extensionRegistry);
      }
      public static PersonMsg.Person.Score parseDelimitedFrom(java.io.InputStream input)
          throws java.io.IOException {
        return PARSER.parseDelimitedFrom(input);
      }
      public static PersonMsg.Person.Score parseDelimitedFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return PARSER.parseDelimitedFrom(input, extensionRegistry);
      }
      public static PersonMsg.Person.Score parseFrom(
          com.google.protobuf.CodedInputStream input)
          throws java.io.IOException {
        return PARSER.parseFrom(input);
      }
      public static PersonMsg.Person.Score parseFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return PARSER.parseFrom(input, extensionRegistry);
      }

      public static Builder newBuilder() { return Builder.create(); }
      public Builder newBuilderForType() { return newBuilder(); }
      public static Builder newBuilder(PersonMsg.Person.Score prototype) {
        return newBuilder().mergeFrom(prototype);
      }
      public Builder toBuilder() { return newBuilder(this); }

      @java.lang.Override
      protected Builder newBuilderForType(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        Builder builder = new Builder(parent);
        return builder;
      }
      /**
       * Protobuf type {@code Person.Score}
       *
       * <pre>
       *嵌套
       * </pre>
       */
      public static final class Builder extends
          com.google.protobuf.GeneratedMessage.Builder<Builder>
         implements PersonMsg.Person.ScoreOrBuilder {
        public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
          return PersonMsg.internal_static_Person_Score_descriptor;
        }

        protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
            internalGetFieldAccessorTable() {
          return PersonMsg.internal_static_Person_Score_fieldAccessorTable
              .ensureFieldAccessorsInitialized(
                  PersonMsg.Person.Score.class, PersonMsg.Person.Score.Builder.class);
        }

        // Construct using PersonMsg.Person.Score.newBuilder()
        private Builder() {
          maybeForceBuilderInitialization();
        }

        private Builder(
            com.google.protobuf.GeneratedMessage.BuilderParent parent) {
          super(parent);
          maybeForceBuilderInitialization();
        }
        private void maybeForceBuilderInitialization() {
          if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          }
        }
        private static Builder create() {
          return new Builder();
        }

        public Builder clear() {
          super.clear();
          chinese_ = 0;
          bitField0_ = (bitField0_ & ~0x00000001);
          history_ = 0;
          bitField0_ = (bitField0_ & ~0x00000002);
          return this;
        }

        public Builder clone() {
          return create().mergeFrom(buildPartial());
        }

        public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
          return PersonMsg.internal_static_Person_Score_descriptor;
        }

        public PersonMsg.Person.Score getDefaultInstanceForType() {
          return PersonMsg.Person.Score.getDefaultInstance();
        }

        public PersonMsg.Person.Score build() {
          PersonMsg.Person.Score result = buildPartial();
          if (!result.isInitialized()) {
            throw newUninitializedMessageException(result);
          }
          return result;
        }

        public PersonMsg.Person.Score buildPartial() {
          PersonMsg.Person.Score result = new PersonMsg.Person.Score(this);
          int from_bitField0_ = bitField0_;
          int to_bitField0_ = 0;
          if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
            to_bitField0_ |= 0x00000001;
          }
          result.chinese_ = chinese_;
          if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
            to_bitField0_ |= 0x00000002;
          }
          result.history_ = history_;
          result.bitField0_ = to_bitField0_;
          onBuilt();
          return result;
        }

        public Builder mergeFrom(com.google.protobuf.Message other) {
          if (other instanceof PersonMsg.Person.Score) {
            return mergeFrom((PersonMsg.Person.Score)other);
          } else {
            super.mergeFrom(other);
            return this;
          }
        }

        public Builder mergeFrom(PersonMsg.Person.Score other) {
          if (other == PersonMsg.Person.Score.getDefaultInstance()) return this;
          if (other.hasChinese()) {
            setChinese(other.getChinese());
          }
          if (other.hasHistory()) {
            setHistory(other.getHistory());
          }
          this.mergeUnknownFields(other.getUnknownFields());
          return this;
        }

        public final boolean isInitialized() {
          return true;
        }

        public Builder mergeFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
          PersonMsg.Person.Score parsedMessage = null;
          try {
            parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
          } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            parsedMessage = (PersonMsg.Person.Score) e.getUnfinishedMessage();
            throw e;
          } finally {
            if (parsedMessage != null) {
              mergeFrom(parsedMessage);
            }
          }
          return this;
        }
        private int bitField0_;

        // optional int32 chinese = 1;
        private int chinese_ ;
        /**
         * <code>optional int32 chinese = 1;</code>
         */
        public boolean hasChinese() {
          return ((bitField0_ & 0x00000001) == 0x00000001);
        }
        /**
         * <code>optional int32 chinese = 1;</code>
         */
        public int getChinese() {
          return chinese_;
        }
        /**
         * <code>optional int32 chinese = 1;</code>
         */
        public Builder setChinese(int value) {
          bitField0_ |= 0x00000001;
          chinese_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>optional int32 chinese = 1;</code>
         */
        public Builder clearChinese() {
          bitField0_ = (bitField0_ & ~0x00000001);
          chinese_ = 0;
          onChanged();
          return this;
        }

        // optional int32 history = 2;
        private int history_ ;
        /**
         * <code>optional int32 history = 2;</code>
         */
        public boolean hasHistory() {
          return ((bitField0_ & 0x00000002) == 0x00000002);
        }
        /**
         * <code>optional int32 history = 2;</code>
         */
        public int getHistory() {
          return history_;
        }
        /**
         * <code>optional int32 history = 2;</code>
         */
        public Builder setHistory(int value) {
          bitField0_ |= 0x00000002;
          history_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>optional int32 history = 2;</code>
         */
        public Builder clearHistory() {
          bitField0_ = (bitField0_ & ~0x00000002);
          history_ = 0;
          onChanged();
          return this;
        }

        // @@protoc_insertion_point(builder_scope:Person.Score)
      }

      static {
        defaultInstance = new Score(true);
        defaultInstance.initFields();
      }

      // @@protoc_insertion_point(class_scope:Person.Score)
    }

    private int bitField0_;
    // required int32 id = 1;
    public static final int ID_FIELD_NUMBER = 1;
    private int id_;
    /**
     * <code>required int32 id = 1;</code>
     *
     * <pre>
     *=后面的数字好像就是序号,一直排下来就是了
     * </pre>
     */
    public boolean hasId() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required int32 id = 1;</code>
     *
     * <pre>
     *=后面的数字好像就是序号,一直排下来就是了
     * </pre>
     */
    public int getId() {
      return id_;
    }

    // required string name = 2;
    public static final int NAME_FIELD_NUMBER = 2;
    private java.lang.Object name_;
    /**
     * <code>required string name = 2;</code>
     */
    public boolean hasName() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required string name = 2;</code>
     */
    public java.lang.String getName() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          name_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string name = 2;</code>
     */
    public com.google.protobuf.ByteString
        getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // optional string email = 3;
    public static final int EMAIL_FIELD_NUMBER = 3;
    private java.lang.Object email_;
    /**
     * <code>optional string email = 3;</code>
     */
    public boolean hasEmail() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>optional string email = 3;</code>
     */
    public java.lang.String getEmail() {
      java.lang.Object ref = email_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          email_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string email = 3;</code>
     */
    public com.google.protobuf.ByteString
        getEmailBytes() {
      java.lang.Object ref = email_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        email_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // repeated string friends = 4;
    public static final int FRIENDS_FIELD_NUMBER = 4;
    private com.google.protobuf.LazyStringList friends_;
    /**
     * <code>repeated string friends = 4;</code>
     */
    public java.util.List<java.lang.String>
        getFriendsList() {
      return friends_;
    }
    /**
     * <code>repeated string friends = 4;</code>
     */
    public int getFriendsCount() {
      return friends_.size();
    }
    /**
     * <code>repeated string friends = 4;</code>
     */
    public java.lang.String getFriends(int index) {
      return friends_.get(index);
    }
    /**
     * <code>repeated string friends = 4;</code>
     */
    public com.google.protobuf.ByteString
        getFriendsBytes(int index) {
      return friends_.getByteString(index);
    }

    // required .Sex sex = 5;
    public static final int SEX_FIELD_NUMBER = 5;
    private PersonMsg.Sex sex_;
    /**
     * <code>required .Sex sex = 5;</code>
     *
     * <pre>
     *引用枚举
     * </pre>
     */
    public boolean hasSex() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>required .Sex sex = 5;</code>
     *
     * <pre>
     *引用枚举
     * </pre>
     */
    public PersonMsg.Sex getSex() {
      return sex_;
    }

    // optional .Info info = 6;
    public static final int INFO_FIELD_NUMBER = 6;
    private PersonMsg.Info info_;
    /**
     * <code>optional .Info info = 6;</code>
     *
     * <pre>
     *引用message
     * </pre>
     */
    public boolean hasInfo() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    /**
     * <code>optional .Info info = 6;</code>
     *
     * <pre>
     *引用message
     * </pre>
     */
    public PersonMsg.Info getInfo() {
      return info_;
    }
    /**
     * <code>optional .Info info = 6;</code>
     *
     * <pre>
     *引用message
     * </pre>
     */
    public PersonMsg.InfoOrBuilder getInfoOrBuilder() {
      return info_;
    }

    // optional .Person.Score score = 7;
    public static final int SCORE_FIELD_NUMBER = 7;
    private PersonMsg.Person.Score score_;
    /**
     * <code>optional .Person.Score score = 7;</code>
     *
     * <pre>
     *引用嵌套message
     * </pre>
     */
    public boolean hasScore() {
      return ((bitField0_ & 0x00000020) == 0x00000020);
    }
    /**
     * <code>optional .Person.Score score = 7;</code>
     *
     * <pre>
     *引用嵌套message
     * </pre>
     */
    public PersonMsg.Person.Score getScore() {
      return score_;
    }
    /**
     * <code>optional .Person.Score score = 7;</code>
     *
     * <pre>
     *引用嵌套message
     * </pre>
     */
    public PersonMsg.Person.ScoreOrBuilder getScoreOrBuilder() {
      return score_;
    }

    private void initFields() {
      id_ = 0;
      name_ = "";
      email_ = "";
      friends_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      sex_ = PersonMsg.Sex.MALE;
      info_ = PersonMsg.Info.getDefaultInstance();
      score_ = PersonMsg.Person.Score.getDefaultInstance();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasName()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasSex()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1, id_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, getNameBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeBytes(3, getEmailBytes());
      }
      for (int i = 0; i < friends_.size(); i++) {
        output.writeBytes(4, friends_.getByteString(i));
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeEnum(5, sex_.getNumber());
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        output.writeMessage(6, info_);
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        output.writeMessage(7, score_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, id_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, getNameBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(3, getEmailBytes());
      }
      {
        int dataSize = 0;
        for (int i = 0; i < friends_.size(); i++) {
          dataSize += com.google.protobuf.CodedOutputStream
            .computeBytesSizeNoTag(friends_.getByteString(i));
        }
        size += dataSize;
        size += 1 * getFriendsList().size();
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(5, sex_.getNumber());
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(6, info_);
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(7, score_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static PersonMsg.Person parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static PersonMsg.Person parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static PersonMsg.Person parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static PersonMsg.Person parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static PersonMsg.Person parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static PersonMsg.Person parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static PersonMsg.Person parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static PersonMsg.Person parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static PersonMsg.Person parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static PersonMsg.Person parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(PersonMsg.Person prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code Person}
     *
     * <pre>
     *3.0版本不写限定符默认都是optional
     *optional,可选,3.0版本没有了
     *required,必须要的,3.0版本没有了
     *repeated,重复的,对应java的list
     * </pre>
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements PersonMsg.PersonOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return PersonMsg.internal_static_Person_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return PersonMsg.internal_static_Person_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                PersonMsg.Person.class, PersonMsg.Person.Builder.class);
      }

      // Construct using PersonMsg.Person.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getInfoFieldBuilder();
          getScoreFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        id_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        name_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        email_ = "";
        bitField0_ = (bitField0_ & ~0x00000004);
        friends_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000008);
        sex_ = PersonMsg.Sex.MALE;
        bitField0_ = (bitField0_ & ~0x00000010);
        if (infoBuilder_ == null) {
          info_ = PersonMsg.Info.getDefaultInstance();
        } else {
          infoBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000020);
        if (scoreBuilder_ == null) {
          score_ = PersonMsg.Person.Score.getDefaultInstance();
        } else {
          scoreBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000040);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return PersonMsg.internal_static_Person_descriptor;
      }

      public PersonMsg.Person getDefaultInstanceForType() {
        return PersonMsg.Person.getDefaultInstance();
      }

      public PersonMsg.Person build() {
        PersonMsg.Person result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public PersonMsg.Person buildPartial() {
        PersonMsg.Person result = new PersonMsg.Person(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.id_ = id_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.name_ = name_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.email_ = email_;
        if (((bitField0_ & 0x00000008) == 0x00000008)) {
          friends_ = new com.google.protobuf.UnmodifiableLazyStringList(
              friends_);
          bitField0_ = (bitField0_ & ~0x00000008);
        }
        result.friends_ = friends_;
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000008;
        }
        result.sex_ = sex_;
        if (((from_bitField0_ & 0x00000020) == 0x00000020)) {
          to_bitField0_ |= 0x00000010;
        }
        if (infoBuilder_ == null) {
          result.info_ = info_;
        } else {
          result.info_ = infoBuilder_.build();
        }
        if (((from_bitField0_ & 0x00000040) == 0x00000040)) {
          to_bitField0_ |= 0x00000020;
        }
        if (scoreBuilder_ == null) {
          result.score_ = score_;
        } else {
          result.score_ = scoreBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof PersonMsg.Person) {
          return mergeFrom((PersonMsg.Person)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(PersonMsg.Person other) {
        if (other == PersonMsg.Person.getDefaultInstance()) return this;
        if (other.hasId()) {
          setId(other.getId());
        }
        if (other.hasName()) {
          bitField0_ |= 0x00000002;
          name_ = other.name_;
          onChanged();
        }
        if (other.hasEmail()) {
          bitField0_ |= 0x00000004;
          email_ = other.email_;
          onChanged();
        }
        if (!other.friends_.isEmpty()) {
          if (friends_.isEmpty()) {
            friends_ = other.friends_;
            bitField0_ = (bitField0_ & ~0x00000008);
          } else {
            ensureFriendsIsMutable();
            friends_.addAll(other.friends_);
          }
          onChanged();
        }
        if (other.hasSex()) {
          setSex(other.getSex());
        }
        if (other.hasInfo()) {
          mergeInfo(other.getInfo());
        }
        if (other.hasScore()) {
          mergeScore(other.getScore());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasId()) {
          
          return false;
        }
        if (!hasName()) {
          
          return false;
        }
        if (!hasSex()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        PersonMsg.Person parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (PersonMsg.Person) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // required int32 id = 1;
      private int id_ ;
      /**
       * <code>required int32 id = 1;</code>
       *
       * <pre>
       *=后面的数字好像就是序号,一直排下来就是了
       * </pre>
       */
      public boolean hasId() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required int32 id = 1;</code>
       *
       * <pre>
       *=后面的数字好像就是序号,一直排下来就是了
       * </pre>
       */
      public int getId() {
        return id_;
      }
      /**
       * <code>required int32 id = 1;</code>
       *
       * <pre>
       *=后面的数字好像就是序号,一直排下来就是了
       * </pre>
       */
      public Builder setId(int value) {
        bitField0_ |= 0x00000001;
        id_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 id = 1;</code>
       *
       * <pre>
       *=后面的数字好像就是序号,一直排下来就是了
       * </pre>
       */
      public Builder clearId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        id_ = 0;
        onChanged();
        return this;
      }

      // required string name = 2;
      private java.lang.Object name_ = "";
      /**
       * <code>required string name = 2;</code>
       */
      public boolean hasName() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required string name = 2;</code>
       */
      public java.lang.String getName() {
        java.lang.Object ref = name_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          name_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string name = 2;</code>
       */
      public com.google.protobuf.ByteString
          getNameBytes() {
        java.lang.Object ref = name_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          name_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string name = 2;</code>
       */
      public Builder setName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        name_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string name = 2;</code>
       */
      public Builder clearName() {
        bitField0_ = (bitField0_ & ~0x00000002);
        name_ = getDefaultInstance().getName();
        onChanged();
        return this;
      }
      /**
       * <code>required string name = 2;</code>
       */
      public Builder setNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        name_ = value;
        onChanged();
        return this;
      }

      // optional string email = 3;
      private java.lang.Object email_ = "";
      /**
       * <code>optional string email = 3;</code>
       */
      public boolean hasEmail() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>optional string email = 3;</code>
       */
      public java.lang.String getEmail() {
        java.lang.Object ref = email_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          email_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string email = 3;</code>
       */
      public com.google.protobuf.ByteString
          getEmailBytes() {
        java.lang.Object ref = email_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          email_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string email = 3;</code>
       */
      public Builder setEmail(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        email_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string email = 3;</code>
       */
      public Builder clearEmail() {
        bitField0_ = (bitField0_ & ~0x00000004);
        email_ = getDefaultInstance().getEmail();
        onChanged();
        return this;
      }
      /**
       * <code>optional string email = 3;</code>
       */
      public Builder setEmailBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        email_ = value;
        onChanged();
        return this;
      }

      // repeated string friends = 4;
      private com.google.protobuf.LazyStringList friends_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      private void ensureFriendsIsMutable() {
        if (!((bitField0_ & 0x00000008) == 0x00000008)) {
          friends_ = new com.google.protobuf.LazyStringArrayList(friends_);
          bitField0_ |= 0x00000008;
         }
      }
      /**
       * <code>repeated string friends = 4;</code>
       */
      public java.util.List<java.lang.String>
          getFriendsList() {
        return java.util.Collections.unmodifiableList(friends_);
      }
      /**
       * <code>repeated string friends = 4;</code>
       */
      public int getFriendsCount() {
        return friends_.size();
      }
      /**
       * <code>repeated string friends = 4;</code>
       */
      public java.lang.String getFriends(int index) {
        return friends_.get(index);
      }
      /**
       * <code>repeated string friends = 4;</code>
       */
      public com.google.protobuf.ByteString
          getFriendsBytes(int index) {
        return friends_.getByteString(index);
      }
      /**
       * <code>repeated string friends = 4;</code>
       */
      public Builder setFriends(
          int index, java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureFriendsIsMutable();
        friends_.set(index, value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string friends = 4;</code>
       */
      public Builder addFriends(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureFriendsIsMutable();
        friends_.add(value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string friends = 4;</code>
       */
      public Builder addAllFriends(
          java.lang.Iterable<java.lang.String> values) {
        ensureFriendsIsMutable();
        super.addAll(values, friends_);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string friends = 4;</code>
       */
      public Builder clearFriends() {
        friends_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000008);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string friends = 4;</code>
       */
      public Builder addFriendsBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureFriendsIsMutable();
        friends_.add(value);
        onChanged();
        return this;
      }

      // required .Sex sex = 5;
      private PersonMsg.Sex sex_ = PersonMsg.Sex.MALE;
      /**
       * <code>required .Sex sex = 5;</code>
       *
       * <pre>
       *引用枚举
       * </pre>
       */
      public boolean hasSex() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      /**
       * <code>required .Sex sex = 5;</code>
       *
       * <pre>
       *引用枚举
       * </pre>
       */
      public PersonMsg.Sex getSex() {
        return sex_;
      }
      /**
       * <code>required .Sex sex = 5;</code>
       *
       * <pre>
       *引用枚举
       * </pre>
       */
      public Builder setSex(PersonMsg.Sex value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000010;
        sex_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required .Sex sex = 5;</code>
       *
       * <pre>
       *引用枚举
       * </pre>
       */
      public Builder clearSex() {
        bitField0_ = (bitField0_ & ~0x00000010);
        sex_ = PersonMsg.Sex.MALE;
        onChanged();
        return this;
      }

      // optional .Info info = 6;
      private PersonMsg.Info info_ = PersonMsg.Info.getDefaultInstance();
      private com.google.protobuf.SingleFieldBuilder<
          PersonMsg.Info, PersonMsg.Info.Builder, PersonMsg.InfoOrBuilder> infoBuilder_;
      /**
       * <code>optional .Info info = 6;</code>
       *
       * <pre>
       *引用message
       * </pre>
       */
      public boolean hasInfo() {
        return ((bitField0_ & 0x00000020) == 0x00000020);
      }
      /**
       * <code>optional .Info info = 6;</code>
       *
       * <pre>
       *引用message
       * </pre>
       */
      public PersonMsg.Info getInfo() {
        if (infoBuilder_ == null) {
          return info_;
        } else {
          return infoBuilder_.getMessage();
        }
      }
      /**
       * <code>optional .Info info = 6;</code>
       *
       * <pre>
       *引用message
       * </pre>
       */
      public Builder setInfo(PersonMsg.Info value) {
        if (infoBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          info_ = value;
          onChanged();
        } else {
          infoBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000020;
        return this;
      }
      /**
       * <code>optional .Info info = 6;</code>
       *
       * <pre>
       *引用message
       * </pre>
       */
      public Builder setInfo(
          PersonMsg.Info.Builder builderForValue) {
        if (infoBuilder_ == null) {
          info_ = builderForValue.build();
          onChanged();
        } else {
          infoBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000020;
        return this;
      }
      /**
       * <code>optional .Info info = 6;</code>
       *
       * <pre>
       *引用message
       * </pre>
       */
      public Builder mergeInfo(PersonMsg.Info value) {
        if (infoBuilder_ == null) {
          if (((bitField0_ & 0x00000020) == 0x00000020) &&
              info_ != PersonMsg.Info.getDefaultInstance()) {
            info_ =
              PersonMsg.Info.newBuilder(info_).mergeFrom(value).buildPartial();
          } else {
            info_ = value;
          }
          onChanged();
        } else {
          infoBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000020;
        return this;
      }
      /**
       * <code>optional .Info info = 6;</code>
       *
       * <pre>
       *引用message
       * </pre>
       */
      public Builder clearInfo() {
        if (infoBuilder_ == null) {
          info_ = PersonMsg.Info.getDefaultInstance();
          onChanged();
        } else {
          infoBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000020);
        return this;
      }
      /**
       * <code>optional .Info info = 6;</code>
       *
       * <pre>
       *引用message
       * </pre>
       */
      public PersonMsg.Info.Builder getInfoBuilder() {
        bitField0_ |= 0x00000020;
        onChanged();
        return getInfoFieldBuilder().getBuilder();
      }
      /**
       * <code>optional .Info info = 6;</code>
       *
       * <pre>
       *引用message
       * </pre>
       */
      public PersonMsg.InfoOrBuilder getInfoOrBuilder() {
        if (infoBuilder_ != null) {
          return infoBuilder_.getMessageOrBuilder();
        } else {
          return info_;
        }
      }
      /**
       * <code>optional .Info info = 6;</code>
       *
       * <pre>
       *引用message
       * </pre>
       */
      private com.google.protobuf.SingleFieldBuilder<
          PersonMsg.Info, PersonMsg.Info.Builder, PersonMsg.InfoOrBuilder> 
          getInfoFieldBuilder() {
        if (infoBuilder_ == null) {
          infoBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              PersonMsg.Info, PersonMsg.Info.Builder, PersonMsg.InfoOrBuilder>(
                  info_,
                  getParentForChildren(),
                  isClean());
          info_ = null;
        }
        return infoBuilder_;
      }

      // optional .Person.Score score = 7;
      private PersonMsg.Person.Score score_ = PersonMsg.Person.Score.getDefaultInstance();
      private com.google.protobuf.SingleFieldBuilder<
          PersonMsg.Person.Score, PersonMsg.Person.Score.Builder, PersonMsg.Person.ScoreOrBuilder> scoreBuilder_;
      /**
       * <code>optional .Person.Score score = 7;</code>
       *
       * <pre>
       *引用嵌套message
       * </pre>
       */
      public boolean hasScore() {
        return ((bitField0_ & 0x00000040) == 0x00000040);
      }
      /**
       * <code>optional .Person.Score score = 7;</code>
       *
       * <pre>
       *引用嵌套message
       * </pre>
       */
      public PersonMsg.Person.Score getScore() {
        if (scoreBuilder_ == null) {
          return score_;
        } else {
          return scoreBuilder_.getMessage();
        }
      }
      /**
       * <code>optional .Person.Score score = 7;</code>
       *
       * <pre>
       *引用嵌套message
       * </pre>
       */
      public Builder setScore(PersonMsg.Person.Score value) {
        if (scoreBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          score_ = value;
          onChanged();
        } else {
          scoreBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000040;
        return this;
      }
      /**
       * <code>optional .Person.Score score = 7;</code>
       *
       * <pre>
       *引用嵌套message
       * </pre>
       */
      public Builder setScore(
          PersonMsg.Person.Score.Builder builderForValue) {
        if (scoreBuilder_ == null) {
          score_ = builderForValue.build();
          onChanged();
        } else {
          scoreBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000040;
        return this;
      }
      /**
       * <code>optional .Person.Score score = 7;</code>
       *
       * <pre>
       *引用嵌套message
       * </pre>
       */
      public Builder mergeScore(PersonMsg.Person.Score value) {
        if (scoreBuilder_ == null) {
          if (((bitField0_ & 0x00000040) == 0x00000040) &&
              score_ != PersonMsg.Person.Score.getDefaultInstance()) {
            score_ =
              PersonMsg.Person.Score.newBuilder(score_).mergeFrom(value).buildPartial();
          } else {
            score_ = value;
          }
          onChanged();
        } else {
          scoreBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000040;
        return this;
      }
      /**
       * <code>optional .Person.Score score = 7;</code>
       *
       * <pre>
       *引用嵌套message
       * </pre>
       */
      public Builder clearScore() {
        if (scoreBuilder_ == null) {
          score_ = PersonMsg.Person.Score.getDefaultInstance();
          onChanged();
        } else {
          scoreBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000040);
        return this;
      }
      /**
       * <code>optional .Person.Score score = 7;</code>
       *
       * <pre>
       *引用嵌套message
       * </pre>
       */
      public PersonMsg.Person.Score.Builder getScoreBuilder() {
        bitField0_ |= 0x00000040;
        onChanged();
        return getScoreFieldBuilder().getBuilder();
      }
      /**
       * <code>optional .Person.Score score = 7;</code>
       *
       * <pre>
       *引用嵌套message
       * </pre>
       */
      public PersonMsg.Person.ScoreOrBuilder getScoreOrBuilder() {
        if (scoreBuilder_ != null) {
          return scoreBuilder_.getMessageOrBuilder();
        } else {
          return score_;
        }
      }
      /**
       * <code>optional .Person.Score score = 7;</code>
       *
       * <pre>
       *引用嵌套message
       * </pre>
       */
      private com.google.protobuf.SingleFieldBuilder<
          PersonMsg.Person.Score, PersonMsg.Person.Score.Builder, PersonMsg.Person.ScoreOrBuilder> 
          getScoreFieldBuilder() {
        if (scoreBuilder_ == null) {
          scoreBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              PersonMsg.Person.Score, PersonMsg.Person.Score.Builder, PersonMsg.Person.ScoreOrBuilder>(
                  score_,
                  getParentForChildren(),
                  isClean());
          score_ = null;
        }
        return scoreBuilder_;
      }

      // @@protoc_insertion_point(builder_scope:Person)
    }

    static {
      defaultInstance = new Person(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:Person)
  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_Info_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_Info_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_Person_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_Person_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_Person_Score_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_Person_Score_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\017PersonMsg.proto\"\"\n\004Info\022\n\n\002qq\030\001 \001(\005\022\016\n" +
      "\006weixin\030\002 \001(\005\"\263\001\n\006Person\022\n\n\002id\030\001 \002(\005\022\014\n\004" +
      "name\030\002 \002(\t\022\r\n\005email\030\003 \001(\t\022\017\n\007friends\030\004 \003" +
      "(\t\022\021\n\003sex\030\005 \002(\0162\004.Sex\022\023\n\004info\030\006 \001(\0132\005.In" +
      "fo\022\034\n\005score\030\007 \001(\0132\r.Person.Score\032)\n\005Scor" +
      "e\022\017\n\007chinese\030\001 \001(\005\022\017\n\007history\030\002 \001(\005*\033\n\003S" +
      "ex\022\010\n\004MALE\020\000\022\n\n\006FEMALE\020\001"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_Info_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_Info_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_Info_descriptor,
              new java.lang.String[] { "Qq", "Weixin", });
          internal_static_Person_descriptor =
            getDescriptor().getMessageTypes().get(1);
          internal_static_Person_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_Person_descriptor,
              new java.lang.String[] { "Id", "Name", "Email", "Friends", "Sex", "Info", "Score", });
          internal_static_Person_Score_descriptor =
            internal_static_Person_descriptor.getNestedTypes().get(0);
          internal_static_Person_Score_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_Person_Score_descriptor,
              new java.lang.String[] { "Chinese", "History", });
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
